import React, { useState } from 'react';
import { StudentResult } from '../types';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, ReferenceLine } from 'recharts';
import { Award, Book, Share2, Download, ArrowLeft, PartyPopper, Check, Copy, AlertCircle } from 'lucide-react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ResultsViewProps {
  result: StudentResult;
  onReset: () => void;
}

const ResultsView: React.FC<ResultsViewProps> = ({ result, onReset }) => {
  const [shareStatus, setShareStatus] = useState<'idle' | 'copied' | 'shared'>('idle');

  const chartData = result.subjects.map(sub => ({
    name: sub.code.replace(/[^a-zA-Z0-9]/g, '').substring(0, 6),
    points: sub.gradePoints || 0,
    credits: sub.credits,
    fullTitle: sub.name
  }));

  const getBarColor = (points: number) => {
    if (points >= 9) return '#4ade80'; // Green
    if (points >= 7) return '#60a5fa'; // Blue
    if (points >= 5) return '#fbbf24'; // Yellow
    return '#f87171'; // Red
  };

  // --- PDF GENERATION LOGIC ---
  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF();

      // 1. Header Background
      doc.setFillColor(79, 70, 229); // Indigo 600
      doc.rect(0, 0, 210, 40, 'F');

      // 2. Title
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text("VTU Grade Genius", 14, 20);
      
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.text("Official Grade Report", 14, 28);

      // 3. Student Details Section
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(11);
      
      let yPos = 55;
      const leftColX = 14;
      const rightColX = 110;

      doc.setFont("helvetica", "bold");
      doc.text("Student Name:", leftColX, yPos);
      doc.setFont("helvetica", "normal");
      doc.text(result.name || "N/A", leftColX + 35, yPos);

      doc.setFont("helvetica", "bold");
      doc.text("USN:", rightColX, yPos);
      doc.setFont("helvetica", "normal");
      doc.text(result.usn || "N/A", rightColX + 15, yPos);

      yPos += 10;
      doc.setFont("helvetica", "bold");
      doc.text("Semester:", leftColX, yPos);
      doc.setFont("helvetica", "normal");
      doc.text(result.semester?.toString() || "N/A", leftColX + 35, yPos);

      doc.setFont("helvetica", "bold");
      doc.text("Scheme:", rightColX, yPos);
      doc.setFont("helvetica", "normal");
      doc.text(result.scheme || "N/A", rightColX + 20, yPos);

      // 4. Score Highlight
      yPos += 15;
      doc.setFillColor(243, 244, 246); // Gray 100
      doc.roundedRect(14, yPos, 182, 25, 3, 3, 'F');
      
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(79, 70, 229);
      doc.text(`SGPA: ${result.sgpa} / 10`, 20, yPos + 16);
      
      doc.setTextColor(20, 184, 166); // Teal
      doc.text(`Credits Earned: ${result.totalCredits}`, 110, yPos + 16);

      // 5. Subject Table
      autoTable(doc, {
        startY: yPos + 35,
        head: [['Code', 'Subject Name', 'Credits', 'Grade Points', 'Result']],
        body: result.subjects.map(sub => [
          sub.code,
          sub.name,
          sub.credits,
          sub.gradePoints || 0,
          (sub.gradePoints || 0) >= 4 ? 'Pass' : 'Fail'
        ]),
        headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        styles: { fontSize: 10, cellPadding: 4 },
        columnStyles: {
          0: { fontStyle: 'bold', cellWidth: 25 },
          1: { cellWidth: 'auto' },
          2: { halign: 'center', cellWidth: 20 },
          3: { halign: 'center', cellWidth: 30 },
          4: { halign: 'center', cellWidth: 25 }
        }
      });

      // 6. Footer
      const pageCount = (doc as any).internal.getNumberOfPages();
      for(let i = 1; i <= pageCount; i++) {
          doc.setPage(i);
          doc.setFontSize(9);
          doc.setTextColor(150);
          doc.text('Generated by VTU Grade Genius', 14, 285);
          doc.text(`Page ${i} of ${pageCount}`, 190, 285, { align: 'right' });
      }

      // Save
      doc.save(`VTU_Result_${result.name || 'Student'}_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (err: any) {
      console.error("PDF Generation Error:", err);
      alert("Failed to generate PDF. Please ensure you ran 'npm install'. Error: " + err.message);
    }
  };

  // --- SHARE LOGIC ---
  const handleShare = async () => {
    const text = `🎓 *VTU Result Update*\n\nName: ${result.name || 'Student'}\nSGPA: ${result.sgpa}\nTotal Credits: ${result.totalCredits}\n\nGenerated by VTU Grade Genius`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My VTU Result',
          text: text,
          url: window.location.href,
        });
        setShareStatus('shared');
      } catch (err) {
        console.log('Error sharing:', err);
      }
    } else {
      // Fallback to clipboard
      try {
        await navigator.clipboard.writeText(text);
        setShareStatus('copied');
        setTimeout(() => setShareStatus('idle'), 2000);
      } catch (err: any) {
        console.error('Failed to copy', err);
        alert("Could not copy to clipboard. Permission denied or not supported.");
      }
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-8 duration-700">
      <button 
        onClick={onReset}
        className="flex items-center text-gray-600 font-bold hover:text-indigo-600 transition-colors mb-2 bg-white/50 px-4 py-2 rounded-full w-fit backdrop-blur-sm"
      >
        <ArrowLeft className="h-4 w-4 mr-2" /> Back to Calculator
      </button>

      {/* Gradient Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        
        {/* SGPA Card */}
        <div className="relative overflow-hidden bg-gradient-to-br from-violet-600 to-indigo-600 rounded-3xl p-8 text-white shadow-2xl shadow-indigo-300 transform hover:scale-[1.02] transition-transform duration-300">
          <div className="absolute top-0 right-0 -mt-4 -mr-4 w-32 h-32 bg-white opacity-10 rounded-full blur-2xl"></div>
          <div className="flex items-center justify-between mb-6">
            <span className="text-indigo-100 font-bold tracking-wider text-sm uppercase">SGPA Score</span>
            <div className="p-2 bg-white/20 rounded-lg backdrop-blur-md">
              <Award className="h-6 w-6 text-white" />
            </div>
          </div>
          <div className="flex items-baseline gap-2">
             <div className="text-6xl font-extrabold tracking-tight">{result.sgpa}</div>
             <div className="text-indigo-200 text-xl font-medium">/ 10</div>
          </div>
          <div className="mt-4 flex items-center gap-2 text-indigo-200 text-sm font-medium">
            <PartyPopper className="h-4 w-4" /> Semester {result.semester || 'N/A'} Result
          </div>
        </div>

        {/* Credits Card */}
        <div className="relative overflow-hidden bg-gradient-to-br from-emerald-500 to-teal-600 rounded-3xl p-8 text-white shadow-2xl shadow-teal-300 transform hover:scale-[1.02] transition-transform duration-300">
          <div className="absolute bottom-0 left-0 -mb-8 -ml-8 w-40 h-40 bg-yellow-400 opacity-20 rounded-full blur-3xl"></div>
          <div className="flex items-center justify-between mb-6">
            <span className="text-teal-100 font-bold tracking-wider text-sm uppercase">Total Credits</span>
            <div className="p-2 bg-white/20 rounded-lg backdrop-blur-md">
              <Book className="h-6 w-6 text-white" />
            </div>
          </div>
          <div className="text-5xl font-extrabold tracking-tight">{result.totalCredits}</div>
          <div className="mt-4 text-teal-100 text-sm font-medium">Successfully Registered</div>
        </div>

        {/* Student Card */}
        <div className="glass-panel rounded-3xl p-8 shadow-xl flex flex-col justify-between relative overflow-hidden">
           <div className="absolute top-0 right-0 w-full h-2 bg-gradient-to-r from-pink-500 to-orange-500"></div>
           <div>
             <h4 className="text-gray-400 font-bold text-xs uppercase tracking-wider mb-2">Student Profile</h4>
             <p className="font-bold text-gray-900 text-xl truncate">{result.name || "Guest Student"}</p>
             <p className="text-gray-500 font-mono text-sm mt-1 bg-gray-100 px-2 py-1 rounded-md inline-block">{result.usn || "USN: N/A"}</p>
           </div>
           <div className="flex gap-3 mt-6">
             <button 
               onClick={handleShare}
               className="flex-1 flex items-center justify-center gap-2 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 py-2.5 rounded-xl text-sm font-bold transition-colors border border-indigo-100 active:scale-95"
             >
                {shareStatus === 'copied' ? <Check className="h-4 w-4" /> : <Share2 className="h-4 w-4" />}
                {shareStatus === 'copied' ? 'Copied!' : 'Share'}
             </button>
             <button 
               onClick={handleDownloadPDF}
               className="flex-1 flex items-center justify-center gap-2 bg-gray-50 hover:bg-gray-100 text-gray-700 py-2.5 rounded-xl text-sm font-bold transition-colors border border-gray-200 active:scale-95"
             >
                <Download className="h-4 w-4" /> PDF
             </button>
           </div>
        </div>
      </div>

      {/* Chart Section */}
      <div className="glass-panel p-8 rounded-3xl shadow-lg border-t-4 border-indigo-500">
        <h3 className="text-xl font-bold text-gray-900 mb-8">Performance Analysis</h3>
        <div className="h-[350px] w-full">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={chartData} margin={{ top: 20, right: 0, left: 0, bottom: 20 }}>
              <XAxis 
                dataKey="name" 
                axisLine={false} 
                tickLine={false} 
                tick={{fill: '#6b7280', fontSize: 12, fontWeight: 600}} 
                dy={10}
              />
              <Tooltip 
                cursor={{fill: 'rgba(99, 102, 241, 0.1)', radius: 8}}
                content={({ active, payload }) => {
                  if (active && payload && payload.length) {
                    const data = payload[0].payload;
                    return (
                      <div className="bg-gray-900/90 backdrop-blur-xl text-white text-xs p-4 rounded-xl shadow-xl border border-gray-700">
                        <p className="font-bold text-base mb-2 text-white">{data.fullTitle}</p>
                        <div className="flex items-center gap-3 mb-1">
                          <div className="w-2 h-2 rounded-full bg-green-400"></div>
                          <p>Points: <span className="font-bold text-green-400 text-lg">{data.points}</span></p>
                        </div>
                        <div className="flex items-center gap-3">
                          <div className="w-2 h-2 rounded-full bg-gray-400"></div>
                          <p>Credits: <span className="text-gray-300">{data.credits}</span></p>
                        </div>
                      </div>
                    );
                  }
                  return null;
                }}
              />
              <ReferenceLine y={4} stroke="#ef4444" strokeDasharray="3 3" strokeOpacity={0.5} />
              <Bar dataKey="points" radius={[8, 8, 8, 8]} barSize={50}>
                {chartData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={getBarColor(entry.points)} className="hover:opacity-80 transition-opacity cursor-pointer" />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Detailed Table */}
      <div className="glass-panel rounded-3xl shadow-lg overflow-hidden">
        <div className="p-6 border-b border-gray-200/60 bg-gray-50/50">
           <h3 className="text-lg font-bold text-gray-900">Detailed Grade Report</h3>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50/80">
              <tr>
                <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase tracking-wider">Code</th>
                <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase tracking-wider">Subject Name</th>
                <th className="px-6 py-4 text-center text-xs font-bold text-gray-500 uppercase tracking-wider">Credits</th>
                <th className="px-6 py-4 text-center text-xs font-bold text-gray-500 uppercase tracking-wider">Grade Points</th>
                <th className="px-6 py-4 text-center text-xs font-bold text-gray-500 uppercase tracking-wider">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {result.subjects.map((sub, idx) => (
                <tr key={idx} className="hover:bg-indigo-50/30 transition-colors">
                  <td className="px-6 py-5 whitespace-nowrap text-sm font-bold text-indigo-600 font-mono">{sub.code}</td>
                  <td className="px-6 py-5 whitespace-nowrap text-sm font-medium text-gray-800">{sub.name}</td>
                  <td className="px-6 py-5 whitespace-nowrap text-sm text-gray-500 text-center font-medium">{sub.credits}</td>
                  <td className="px-6 py-5 whitespace-nowrap text-center">
                    <span className="inline-flex items-center justify-center w-8 h-8 rounded-full bg-gray-100 text-gray-900 font-bold text-sm">
                      {(sub.gradePoints || 0)}
                    </span>
                  </td>
                  <td className="px-6 py-5 whitespace-nowrap text-center">
                    {(sub.gradePoints || 0) >= 4 ? (
                      <span className="px-3 py-1 inline-flex text-xs leading-5 font-bold rounded-full bg-green-100 text-green-700 border border-green-200 shadow-sm">
                        Pass
                      </span>
                    ) : (
                      <span className="px-3 py-1 inline-flex text-xs leading-5 font-bold rounded-full bg-red-100 text-red-700 border border-red-200 shadow-sm">
                        Fail
                      </span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ResultsView;